name: Pipeline ML
on:
push:
branches:
- main

jobs:

build:

runs-on: ubuntu-latest

steps:

- name: Descargar Repositorio
uses: actions/checkout@v4

- name: Instalar Python
uses: actions/setup-python@v4
with:
python-version: "3.11"

- name: Instalar Dependencias
run: |
pip install -r requirements.txt

- name: Ejecutar Test
run: |
pytest

- name: Entrenar Modelo
run: |
python src/train.py
